### ISSUE TITLE
Wrong volume permissions after container restarts

### ISSUE THREAD

**Issue by ruanbekker** [bitnami/bitnami-docker-jenkins#52]
**Description**

Persistent docker volume causes permission issue when the container starts after its been stopped.

**Steps to reproduce the issue:**

1. Start jenkins with persistent volume
2. Login to jenkins then stop the container
3. Start the container
4. Getting the below error:

```
jenkins_1  | touch: cannot touch '/opt/bitnami/jenkins/copy_reference_file.log': No such file or directory
jenkins_1  | Can not write to /opt/bitnami/jenkins/copy_reference_file.log. Wrong volume permissions?
```

**Describe the results you received:**

Initial start:

```
> docker-compose up
...
jenkins_1  | 2019-10-12 22:27:34.096+0000 [id=20]	INFO	hudson.WebAppMain$3#run: Jenkins is fully up and running
```

Navigate to jenkins ui, login and ensure everything is working.

stop the container:

```
> docker-compose down
Stopping jenkins_jenkins_1 ... done
Removing jenkins_jenkins_1 ... done
Removing network jenkins_default
```

Start the container again:

```
> docker-compose up
Creating network "jenkins_default" with the default driver
Creating jenkins_jenkins_1 ... done
Attaching to jenkins_jenkins_1
jenkins_1  |
jenkins_1  | Welcome to the Bitnami jenkins container
jenkins_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-jenkins
jenkins_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-jenkins/issues
jenkins_1  |
jenkins_1  | touch: cannot touch '/opt/bitnami/jenkins/copy_reference_file.log': No such file or directory
jenkins_1  | Can not write to /opt/bitnami/jenkins/copy_reference_file.log. Wrong volume permissions?
jenkins_jenkins_1 exited with code 1
```

The compose that I use:

```
version: '2'
services:
  jenkins:
    image: 'bitnami/jenkins:2.190.1-debian-9-r14'
    environment:
      - JENKINS_USERNAME=ruan
      - JENKINS_PASSWORD=password123
      - JENKINS_HOME=/opt/bitnami/jenkins/jenkins_home
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/opt/bitnami'
volumes:
  jenkins_data:
    driver: local
```

**Describe the results you expected:**

I expect that after stop/starting the container that it should work and not having a permission denied issue. 

Is there a possibility that you can set the uid from the environment?

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
> docker version
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker-compose version` (if applicable):

```
> docker-compose version
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```
